/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wryktWyAEXQ
 */
import {
    TableHead,
    TableRow,
    TableHeader,
    TableCell,
    TableBody,
    Table,
    TableFooter,
} from '@/components/ui/table';

type Registration = {
    id: number;
    name: string;
    email: string;
    company: string;
    attendance: string;
    registered_date: Date;
};

const attendanceMap: any = {
    both: 'Both',
    'day-one': 'Day 1',
    'day-two': 'Day 2',
};

export function EventRegistrationList({
    registrations,
}: {
    registrations: Registration[];
}) {
    return (
        <Table>
            <TableHeader>
                <TableRow>
                    <TableHead>Name</TableHead>
                    <TableHead>Email</TableHead>
                    <TableHead>Company</TableHead>
                    <TableHead>Attending</TableHead>
                    <TableHead>Registration Date</TableHead>
                </TableRow>
            </TableHeader>
            <TableBody>
                {registrations.map((registration, index) => (
                    <TableRow key={index}>
                        <TableCell>{registration.name}</TableCell>
                        <TableCell>{registration.email}</TableCell>
                        <TableCell>{registration.company}</TableCell>
                        <TableCell>
                            {attendanceMap[registration.attendance]}
                        </TableCell>
                        <TableCell>
                            {new Date(
                                registration.registered_date
                            ).toLocaleDateString()}
                        </TableCell>
                    </TableRow>
                ))}
            </TableBody>
            <TableFooter>
                <TableRow>
                    <TableCell colSpan={5}>{registrations.length}</TableCell>
                </TableRow>
            </TableFooter>
        </Table>
    );
}
