/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wryktWyAEXQ
 */
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import {
    TableHead,
    TableRow,
    TableHeader,
    TableCell,
    TableBody,
    Table,
    TableFooter,
} from '@/components/ui/table';

type Registration = {
    id: number;
    name: string;
    email: string;
    company: string;
    attendance: string;
    registered_date: Date;
};

export function EventRegistrationList({
    registrations,
}: {
    registrations: Registration[];
}) {
    return (
        <div className="flex flex-col w-full min-h-screen px-4 py-6 md:px-6">
            <header className="mb-6">
                <h1 className="text-3xl font-bold">Spring & Grinding Days</h1>
                <p className="text-gray-500 dark:text-gray-400">
                    All registrations for Spring & Grinding Days
                </p>
            </header>
            {/* <div className="flex justify-between items-center mb-4">
                <div className="w-full max-w-md">
                    <Input placeholder="Search participants" type="search" />
                </div>
                <Button className="ml-auto">Export as CSV</Button>
            </div> */}
            <Table>
                <TableHeader>
                    <TableRow>
                        <TableHead>Name</TableHead>
                        <TableHead>Email</TableHead>
                        <TableHead>Company</TableHead>
                        <TableHead>Date</TableHead>
                    </TableRow>
                </TableHeader>
                <TableBody>
                    {registrations.map((registration, index) => (
                        <TableRow key={index}>
                            <TableCell>{registration.name}</TableCell>
                            <TableCell>{registration.email}</TableCell>
                            <TableCell>{registration.company}</TableCell>
                            <TableCell>
                                {new Date(
                                    registration.registered_date
                                ).toLocaleDateString()}
                            </TableCell>
                        </TableRow>
                    ))}
                </TableBody>
                <TableFooter>
                    <TableRow>
                        <TableCell colSpan={4}>
                            {registrations.length}
                        </TableCell>
                    </TableRow>
                </TableFooter>
            </Table>
        </div>
    );
}
